version: '2'
services:
  mariadb:
    image: 'wodby/mariadb:10-3.9.4'
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - '3306:3306'
  php:
    image: 'wodby/drupal-php:7.4-4.19.2'
    container_name: php
    environment:
      VAGRANT_MACHINE: 1
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_SENDMAIL_PATH: '/usr/sbin/sendmail -t -i -S mailhog:1025'
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_XDEBUG_REMOTE_HOST: 192.168.33.1
      PHP_FPM_CLEAR_ENV: 'no'
      SSH_DISABLE_STRICT_KEY_CHECKING: 0
      SSH_PRIVATE_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEAuH4+oCnC6wx+ySi1rN0LVheynZdoVDKyGPHW2Fa5IfHNaVVY\n+GLu4vAu2YR4FahKWI13FLdelgRcJrDwGzQSto8WL7bxsjXNevRSb4N4+6gbnV1B\nR/tv65wTuazIo+KQdTxGtiqWUt/nIMt57x8KoxbgIyV98drD0QXY5V4ohQJ7EtTi\nrgtF9DRtMV2V8CW3IHQPQZN3wbdV14vOs3wRwIzbRH4r68YRxl5QL1n+m/ys7xf3\nxCdLplGi+JT9gSGNdzoQlKz/NPi5RFySeAVeSN8l9jkD9AhKL26a6uCp97bTUU9r\n93u3eKxPxHggW/CharbSGYCYXYr2i0YwTMudAQIDAQABAoIBAH/J4fLqOjq4svD+\no6gSi5GcZHnHr9nyK24fxOKgXydl5xO4rCGP1UuXdbvwh4ToxmZDxmGxCXD7oCCk\nmgsdrICK56ExJIR9w9AQfzECbcBSFp6PQ3JqdIFL4FXRmj/55HlvwMLZCLpqoBsV\nFWZNp/6DD8kIZQ4qq0uSs0NcTtChU5jx04oYLrHCZ72ua+vyEvntT0AV+p1gkoLz\nlLx+ylVtI8tzPfIhXeUQCKyKo1sHXLph0dl7gugy9V9oiGUBy5uP6zv90rkUtx6l\n5skDY/n3VoW9aqDagS/iC26W03zosr25ECGZuK87tec3yggwYHCBXNE761ScBkh+\nHoBmHgECgYEA53LjyGK71wsKhrIbyVYgilaRugSBeQL8Dbh8oNL9Gg/iAQGQ2B5y\nLC1glLT6yH7ct4psSz0vQE7/SblHd7FAkbPl0gu+dQVfSAFL8MmAJ8gy5yJB2Q8e\n3RQNt5IXEP5s5W3aMG4/QuZV27OGXLhd+5cil/M/dcUDqsQoDbmxXtECgYEAzBBA\nE2FuFc6M3YegCacmJk2cN0YKnVqz1pP9CHPkljz1d7xfrXCj/TPDJovqKINdecmx\nmBfz/jD/DjHQSvXu5fbatVN5e2fCxIQa92LH3ckTphTU3bAQLkIO/rTHGr2N1Lj+\nV1iuSBq1zMJamH8vNVX3NFN6qo+8CBytmT/kxzECgYAqRd+4v9/THR8lDu7oTSTQ\nX5NqSFxlf9gNoX6R2TeFRRVgXarY7maoDvmu74dGi3VAyLWS4G/67PLPwll9URCc\nDCGTxbVZpkuK2UHHjuYrXfN+J9GjFZHrizgeKT6xSecV2ISbh+diDrPr1tRZpwrz\nYt1cp38VwZAz5nPyXdI5oQKBgGCvFlzYXbsxSOaxGq9YJagiP3Ck2+SgE/MH3OxD\nVLumGDtp4f8gDmKqQr0hr4kQbJqGaIGCX9VAy6ejDGhny4/jfM5KxZUlnU9UtB4g\nDEhVu9yFpDGA+LmiDM67Qla2FtwB5mfmGXUKSrbAIwJ7yBdCKsT9BHKJdXJ2e/3P\nGwsRAoGAHiTTObLehg0oCFzVczbfs2mHG96z4OcQ684x/qQFOwWpo1IYqHibeXz0\nKV0rrl3d/h6Yh2WCnCMkGtu4C0D819CP8tPspyLBCIWWK2O49lHlWBqJ2pl45E2A\n9ndhEn3kLnnsyf3Gc9217TYiW9q/PskltAg/3E+RsBn48VMB/O8=\n-----END RSA PRIVATE KEY-----\n"
    extra_hosts:
      - 'mideafinancesystem.local:172.18.0.1'
    volumes:
      - '../..:/app'
  nginx:
    image: 'wodby/nginx:1.15-5.10.7'
    container_name: nginx
    depends_on:
      - php
    environment:
      VAGRANT_MACHINE: 1
      NGINX_USER: wodby
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: '/app/source/drupal/docroot'
      NGINX_VHOST_PRESET: drupal8
    volumes:
      - '../..:/app'
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - 'traefik.http.routers.nginx.rule=Host(`mideafinancesystem.local`,`frontend.mideafinancesystem.local`)'
  adminer:
    image: clue/adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - traefik.enable=true
      - traefik.http.services.adminer.loadbalancer.server.port=80
      - 'traefik.http.routers.adminer.rule=Host(`adminer.mideafinancesystem.local`)'
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: mailhog
    labels:
      - traefik.enable=true
      - traefik.http.services.mailhog-config.loadbalancer.server.port=8025
      - 'traefik.http.routers.mailhog.rule=Host(`mailhog.mideafinancesystem.local`)'
  portainer:
    image: portainer/portainer
    command: '--no-auth -H unix:///var/run/docker.sock'
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    labels:
      - traefik.enable=true
      - traefik.http.services.portainer-config.loadbalancer.server.port=9000
      - 'traefik.http.routers.portainer.rule=Host(`portainer.mideafinancesystem.local`)'
  traefik:
    image: 'traefik:2.3.2'
    container_name: traefik
    restart: unless-stopped
    command:
      - '--log.level=INFO'
      - '--api.insecure=true'
      - '--providers.docker=true'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
