host: mideafinancesystem.local
adminer: adminer.mideafinancesystem.local
mailhog: mailhog.mideafinancesystem.local
portainer: portainer.mideafinancesystem.local
frontend: frontend.mideafinancesystem.local
